# Server settings
server:
    port: 8080
    address: localhost
    session:
      timeout: 10
    tomcat:
      uri-encoding: UTF-8
# Actuator setting
management:
    #指定监控HTTP端口，如果没有配置,默认与server配置端口相同
    port: 8080
    #指定去掉某项的检查（不监控health.db）
    health:
      db:
        enabled: false

# SPRING PROFILES
spring:
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
#THYMELEAF Setting【spring boot 默认用的模板引擎就是thymeleaf 可以不用配置】
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      encoding: UTF-8
      content-type: text/html
      #不使用thymeleaf的缓存处理
      cache: false

    #Redis Setting
    redis:
      host: 10.6.60.38
      password: 11112222
      port: 6379
      pool:
        max-idle: 10
        min-idle: 5
        max-active: 8
        max-wait: 3000
        max-total: 30

    #Elasticsearch Setting
    data:
      elasticsearch:
        cluster-name: my-application
        cluster-nodes: 10.6.60.38:9300
        repositories:
          enable: true


    devtools:
        restart:
          enabled: true

    #RabbitMQ Setting
    rabbitmq:
      addresses: 10.6.60.33:5672
      #如果要进行消息回调，则这里必须要设置为true
      publisher-confirms: true
      

    # Kafka Setting
    kafka:
        producer:
          bootstrap-servers: 10.6.60.215:9092
          retries: 0
          batch-size: 16384
          buffer-memory: 33554432
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.apache.kafka.common.serialization.StringSerializer
        consumer:
          bootstrap-servers: 10.6.60.215:9092
          group-id: foo
          auto-offset-reset: earliest
          enable-auto-commit: true
          auto-commit-interval: 100
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


    # FREEMARKER Setting
#    freemarker:
#      allow-request-override: false
#      cache: true
#      check-template-location: true
#      charset: UTF-8
#      content-type: text/html
#      expose-request-attributes: false
#      expose-session-attributes: false
#      expose-spring-macro-helpers: false
#      template-loader-path: /WEB-INF/templates/


# DATASOURCE CONFIGERATION - C3P0 ConnectPool :DatasourceConfiguration
c3p0:
    jdbcUrl: jdbc:mysql://10.6.60.38:3306/tis?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    user: root
    password: 11112222
    deiverClass: com.mysql.jdbc.Driver
    minPoolSize: 2
    maxPoolSize: 10
    maxIdelTime: 1800000
    initialPoolSize: 3
    acquireIncrement: 3
    acquireRetryAttempts: 30
    maxStatements: 1000

# MyBatis
mybatis:
    mapperLocations: classpath:/mybatis/mappers/*.xml
    cacheEnabled: true
    lazyLoadingEnabled: true
    useGeneratedKeys: false
    autoMappingBehavior: PARTIAL
    lazyLoadTriggerMethods: equals,clone,hashCode,toString
    jdbcTypeForNull: NULL
    defaultStatementTimeout: 25000

#Logback
logging:
    config: classpath:etc/logback.xml


# Kafka Setting
#kafka:
#    binder:
#      brokers: 10.6.60.38:9092
##      zk-nodes: 10.6.60.38:2181
#    group: foo


